apiVersion: v1
kind: Service
metadata:
  name: service-internal-api
  labels:
    app: internal-api
    tier: web
spec:
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8000
  selector:
    app: internal-api
    tier: web
